### ISSUE TITLE
Safe handling of service instance params (user input) in gotemplates

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry-incubator/service-fabrik-broker#1306]
**Is your feature request related to a problem? Please describe.**
Hi folks!

In our use case, we require the user to input service instance parameters when creating service instances. Since it's untrusted user input, we need to handle it carefully (i.e. validate it etc.).

These service instance parameters - currently, it's just simple string values - are passed as is to our operator's CR's `Spec`.

Our `provision` template looks as follows (simplified:
```
  templates:
    - action: provision
      content: |
        apiVersion: <some-resource>/v1alpha1
        kind: <some-kind>
        metadata:
          name: {{ .instance.metadata.name }}
        spec:
          param1: {{ .instance.spec.parameters.param1 }}
          param2: {{ .instance.spec.parameters.param2 }}
```

This works fine, as long as `param1` is a simple string without YAML-related special chars.

If the user however inputs some chars as `param1` that confuse the YAML templating (we used `"{}'\"\n"` as an example), a `Service Broker Error, status code: ETIMEDOUT, error code: 10008` is received.

The `sfserviceinstances.osb.servicefabrik.io` CR shows the following error:
```
    "status": {
        "appliedSpec": {
            "planId": "",
            "serviceId": ""
        },
        "description": "Service Broker Error, status code: ETIMEDOUT, error code: 10008",
        "error": "Retry threshold reached for de6830ca-46d4-d466-974a-68f544980ff3.\nunable to unmarshal from yaml. error converting YAML to JSON: yaml: line 6: did not find expected key",
        "state": "failed"
    }
```

**Describe the solution you'd like**
Is there a safe way to a.) ensure the input value is actually a string and b.) a safe way to render the string for downstream use?
Maybe some kind of `toString` function?

**Describe alternatives you've considered**
We tried the following YAML hacks, but the error persisted:
```
        spec:
          param1: {{ .instance.spec.parameters.param1 | toYaml }}
```

```
        spec:
          param1: |- 
            {{ .instance.spec.parameters.param1 }}
```

Would be nice if you can point us in the right direction - many thanks :)

**Comment by vivekzhere** [comment]
[OSB api](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#schemas-object) supports validation of input parameters. This feature is supported by inter operator as well as part of [SFPlan](/docs/Interoperator.md#sfplan).

**Comment by vivekzhere** [comment]
Also 
```
        spec:
          param1: |- 
            {{ .instance.spec.parameters.param1 | nindent 12 }}
```
Should also force the passing the parameter as string to the Custom Resource.

Note that the `nindent` value might need to be adjusted

**Comment by MatthiasWinzeler** [comment]
@vivekzhere Thanks for your response! 

I assume these capabilities should be enough to achieve what we want. I'll quickly test them and add my findings here.

**Comment by MatthiasWinzeler** [comment]
@vivekzhere Looks good!
- The schema validation configured in the plan works fine
- The issue with multiline strings etc. works nicely when `nindent`ing. We added a `trim` to get rid of the leading new line that is otherwise always added, so it looks something along the lines of:
```
  templates:
    - action: provision
      content: |
        apiVersion: <some-resource>/v1alpha1
        kind: <some-kind>
        metadata:
          name: {{ .instance.metadata.name }}
        spec:
          param1: |-
            {{ .instance.spec.parameters.param1 | nindent 4 | trim }}
```

Many thanks for your help!
