### ISSUE TITLE
service instance custom error message in status template are not returned

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/service-fabrik-broker#1493]
**Describe the bug**
Thanks for the great work. Testing how to return a custom failed error message, I never see it being returned in SFServiceInstance (and hence nor by the service broker)

**To Reproduce**

Given a SFPlan with the following status template 

```yaml
  templates:
  - action: status
    content: |-
      # Status template for provision call
      provision:
        state: failed
        description: a custom error message
```

When the SFServiceInstance gets provisionned, then its status does not contain the description or error field

```
status:
  appliedSpec:
    planId: ""
    serviceId: ""
  resources:
  - apiVersion: v1
    kind: ConfigMap
    name: instance-sapcp-5a29d700-3c08-4d5e-a68a-3e6cae710ab4
    namespace: sf-5a29d700-3c08-4d5e-a68a-3e6cae710ab4
  state: failed
```

However, when the status template is missing, then a proper error message is returned
```
 status:                                                                                                                                                                                                  │
│   appliedSpec:                                                                                                                                                                                           │
│     planId: ""                                                                                                                                                                                           │
│     serviceId: ""                                                                                                                                                                                        │
│   description: sources template not found for plan 24d7d4c8-6fe2-4c2a-a5ca-b826937d5a88                                                                                                                  │
│   error: |-                                                                                                                                                                                              │
│     Retry threshold reached for 930f66eb-3311-4aa2-8037-16ad164b1384.                                                                                                                                    │
│     sources template not found for plan 24d7d4c8-6fe2-4c2a-a5ca-b826937d5a88                                                                                                                             │
│   state: failed                                                                                                                                                                                          │
```

**Expected behavior**

The SFServiceInstance and service broker should return the description to the osb client, as documented in the OSB specs at https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-1

**Additional context**

Reproduced with helm chart version: 0.19.0

Possibly related to https://github.com/cloudfoundry-incubator/service-fabrik-broker/issues/1305
