### ISSUE TITLE
'validate is not a function' error

### ISSUE THREAD

**Issue by dlapanik** [cloudfoundry-incubator/service-fabrik-broker#1643]
**Describe the bug**
Getting error '**validate is not a function**' when try to create service instance if for SFPlan definition JSON Schema draft-07 was used.

**To Reproduce**

1. Define SFPlan with  **"$schema": "http://json-schema.org/draft-07/schema#"**

```
  schemas:
    service_instance:
      create:
        parameters:
          "$schema": "http://json-schema.org/draft-07/schema#"
          title: createServiceInstance
          type: object
          additionalProperties: false
          _show_form_view: true
          properties:
            backend:
              type: string
```
1. try to create service instance

**Expected behavior**
As soon as you are using https://ajv.js.org for JSON validation I expect that drafts 04, 06, 07, 2019-09 and 2020-12 are supported.

If by some reason you support only draft-04,-06 I expect do not see runtime error but appropriate message (better during applying SFPlan and not when somebody tries to create service instance)

**Additional context**
Error raised from [line 243](https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/f938202bc8664e5b9eaf33c2ae9f66fb2d1e1901/broker/applications/osb-broker/src/api-controllers/middleware/index.js#L243).

Bug was introduced by https://github.com/cloudfoundry-incubator/service-fabrik-broker/commit/eb5a2824a39facf7994db3449b50b218f082cfc4.

If you follow method [validateSchemaForRequest](https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/f938202bc8664e5b9eaf33c2ae9f66fb2d1e1901/broker/applications/osb-broker/src/api-controllers/middleware/index.js#L211) - there are branches only for schema equal draft-04,-06 and "". So of schema defined as draft-07 and code comes to line 243 validate has undefined value
